# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1.4.3
      - run: |
         cd ..
         echo "Laaaaaaaaaaaaaaaaaaaaaa-> "$PWD
         echo "Gaaaaaaaaaaaaaaaaaaaaaa-> "`ls`
         npm ci
         npm run build
         
  test:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/setup-node@v1.4.3
      - run: |
         npm ci
         npm test
