name: CI/CD Pipeline

on:
  push:
  pull_request:

jobs:         
  test:
    runs-on: ubuntu-latest
    env:
      CI: true
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/setup-node@v1.4.3
      - uses: actions/checkout@v2.3.2
      - uses: SonarSource/sonarcloud-github-action@v1.3
      - run: |
         npm ci
         npm test -- --coverage
         
  build:
    runs-on: ubuntu-latest
    steps:
      - needs: test
      - uses: actions/setup-node@v1.4.3
      - uses: actions/checkout@v2.3.2
      - run: |
         npm ci
         npm run build
