name: Praarthi Frontend pipeline

on:
  push:
  pull_request:

jobs:         
  test:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/setup-node@v1.4.3
      - uses: actions/checkout@v2.3.2
      - run: |
         npm ci
         npm test
         
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1.4.3
      - uses: actions/checkout@v2.3.2
      - run: |
         npm ci
         npm run build
